### PR TITLE
Add script to copy files to lib folder 

### PR DESCRIPTION
**Pull request by tbergq**
<br/><br/><br/><url>LiveURL: https://orbit-components-npmignore.surge.sh</url>

### CODE REVIEW

**Comment by tomashapl** [comment]
@tbergq in main repo we are using whitelisting instead of blacklisting, please check `files` section in `package.json` we had some issues with `.npmignore`

**Comment by tbergq** [comment]
Ok, let me see if I can make it work with whitelisting as well

**Comment by tbergq** [comment]
I don't think we can make this work without `.npmignore`.

What was the issue you had with it @tomashapl? 

We want to provide the src to the consumer, but he does not need the stories.

**Comment by tomashapl** [comment]
> I don't think we can make this work without `.npmignore`.
> 
> What was the issue you had with it @tomashapl?
> 
> We want to provide the src to the consumer, but he does not need the stories.

Sometimes `npm publish` completely ignore `.npmignore` ¯\_(ツ)_/¯

**Comment by tbergq** [comment]
Yeah, after adding whitelisting, blacklisting seems to fail. 😞

**Comment by tbergq** [comment]
Ok, so I changed the approach a little bit. I made a script that copies all files expect test folders and `.stories.js` files to lib folder, then whitelist the lib folder.

**Pull request closed without merging**
