### PR TITLE
fix(Browsers): added kiwicom supported browsers to the project

### PR DESCRIPTION
**Pull request by dinodsaurus**
Added a company-wide browser list to the project so we can run tests on it and see if everything behaves as previously 🤞 
Will test it also on few other projects just to ensure that everything behaves the same 😉 
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-supported-browsers.surge.sh</url>

### CODE REVIEW

**Comment by silvenon** [comment]
Also, I think this should be treated as a breaking change, what do you think?

**Comment by dinodsaurus** [comment]
Wow, thanks a lot for pointing this out! ❤️ 
Yea this could be treated as a breaking change 🤔 
This package is still in the testing phase..
Could you pls take over this MR and make it work on orbit and see if there are some big problems occurring 🙏 Also it would be worth to check bundle size

**Comment by silvenon** [comment]
There appears to be no changes in bundle size.

**Comment by filipdanisko** [comment]
Can you also please update this section of readme? As it is in relation to this issue :)  https://github.com/kiwicom/orbit-components/blob/master/.github/contribution/testing-conventions.md#browser-compatibility

**Comment by dinodsaurus** [comment]
Love the last commit! I copied it to our supported browsers package 😍  🦖

**Comment by silvenon** [comment]
@filipdanisko with the last commit we shouldn't have to worry about updating the list anymore. Let me know what you think.

**Pull request merged**
