### PR TITLE
ICONS: Update documentation

### PR DESCRIPTION
**Pull request by wEprous**
Updated `readme.md` for icons.

### CODE REVIEW

**Comment by wEprous** [comment]
Please read that and suggest more improvements (if necessary). cc @darkwindcz @williamkolmacka

**Comment by wEprous** [comment]
We can drop this file and merge documentation with this [file](https://github.com/kiwicom/orbit-components/blob/master/src/Icon/README.md). It was added in #224

**Comment by darkwindcz** [comment]
Can you replace link in "list of icons" to https://orbit.kiwi/visual-style/icons/#icon-list?

**Comment by wEprous** [comment]
Icon list on orbit.kiwi contains different names (not exact component name).
I want to replace that link in the future with stuff from #207 and get rid off PNGs in #215

**Comment by wEprous** [comment]
Icons file `readme.md` deleted in #207

**Pull request closed without merging**
