### PR TITLE
DOCS: Better typing for call backs

### PR DESCRIPTION
**Pull request by wEprous**
Just better typing for docs for callbacks.
<br/><br/><br/><url>LiveURL: https://orbit-components-docs-better-callbacks.surge.sh</url>

### CODE REVIEW

**Comment by tomashapl** [comment]
Nice 👏 I would add also Promise, because you could pass this:

```
onChange={() => new Promise((resolve, reject) => {...})}
```

**Comment by wEprous** [comment]
So, should I update to this format: `() => void | Promise`?

**Comment by tomashapl** [comment]
@wEprous Yes please 🙏

**Comment by wEprous** [comment]
Updated. Somewhere typing for Promises is missing, we should fix it in another PR, I gonna create an issue for that.

**Pull request merged**
