### PR TITLE
NEW: Layout and Grid component

### PR DESCRIPTION
**Pull request by vepor**
This Pull Request meets the following criteria:

* [x] Tests have been added/adjusted for my new feature
* [x] New Components are registered in index.js of my project
<br/><br/><br/><url>LiveURL: https://orbit-components-new-layout-grid-component.surge.sh</url>

### CODE REVIEW

**Comment by Germi41** [comment]
### **Testing IE:**

Layout Search: 
- Middle rectangle is missing -> https://take.ms/CEKhl
- Right rectangle disappearing faster than in Chrome -> https://take.ms/rLmgJ
- The width where all rectangles became one is also different -> https://take.ms/5xMhK

Layout Booking: 
- The breakpoint is different -> http://take.ms/QnR6g

Layout RTL: 
- Middle rectangle is missing -> https://take.ms/Hr8Vn
- Breakpoint are the same like in Search

Grid:
Breakpoint is different again -> https://take.ms/Vq4D3

--------------------------------------------------------------------

Edge is the same as Chrome

**Comment by vepor** [comment]
Can you please review the code while it will be tested once again in IE? @tomashapl @filipdanisko

**Comment by Germi41** [comment]
It is not loading at all in IE

**Comment by vepor** [comment]
Works now @Germi41

**Comment by Germi41** [comment]
Works now the same as in Chrome... just I think that some breakpoints are slightly different, but not sure if it is really bug issue or not :)

**Pull request merged**
